name: sudoku-haskell
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - HUnit
  - QuickCheck
  - random
  - time

library:
  source-dirs: .
  exposed-modules:
    - Sudoku
    - Solver
  other-modules:
    - Generator
    - Benchmark

executables:
  Tests:
    main: Tests.hs
    source-dirs: .
    other-modules: []
    dependencies:
      - sudoku-haskell
